language: python
sudo: false
install:
  - pip install sphinx
script:
  - make html 2> stderr.log
  - cat stderr.log
  # fail the build for any stderr output
  - if [ -s "stderr.log" ]; then false; fi
notifications:
  email: false
