name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies with pip
        run: |
          pip install doc8 sphinx
          pip install git+https://github.com/osrf/sphinx-tabs

      - run: make html 2> stderr.log
      - run: cat stderr.log
      - run: doc8 --ignore D001 --ignore-path build --ignore-path source/Tutorials/Actions
      # ignore D000 in action tutorials to allow for :linenos:
      - run: doc8 --ignore D000 --ignore D001 --ignore-path build source/Tutorials/Actions
      # fail the build for any stderr output
      - run: if [ -s "stderr.log" ]; then false; fi
